# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Qfex < Formula
  desc "CLI for the QFEX perpetual futures exchange"
  homepage "https://github.com/QFEX-org/cli"
  version "0.3.6"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/QFEX-org/cli/releases/download/v0.3.6/cli_0.3.6_darwin_amd64.tar.gz"
      sha256 "c78d4e354567b6783e33157d924711b4f10a9b32e4969d94cb6ba9f656ebcfac"

      define_method(:install) do
        bin.install "qfex"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/QFEX-org/cli/releases/download/v0.3.6/cli_0.3.6_darwin_arm64.tar.gz"
      sha256 "9b839c3dc865a69da18565773c574ecb1bb0564f208df5db043af357fdb6a30a"

      define_method(:install) do
        bin.install "qfex"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/QFEX-org/cli/releases/download/v0.3.6/cli_0.3.6_linux_amd64.tar.gz"
      sha256 "f323d8cfb3bb3153f0456222045a70abfd4b87a2e3e880b86990eff3516da760"
      define_method(:install) do
        bin.install "qfex"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/QFEX-org/cli/releases/download/v0.3.6/cli_0.3.6_linux_arm64.tar.gz"
      sha256 "cee458389694de4fdec8ecd1a7d9d0aeeab0c4b44d3e4dfc80c710c380b41fa3"
      define_method(:install) do
        bin.install "qfex"
      end
    end
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/qfex version")
  end
end
