# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Qfex < Formula
  desc "CLI for the QFEX perpetual futures exchange"
  homepage "https://github.com/QFEX-org/cli"
  version "0.3.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/QFEX-org/cli/releases/download/v0.3.0/cli_0.3.0_darwin_amd64.tar.gz"
      sha256 "808c0abcbd27e758039043c7e078ceb730db58ef5a1eea40906ff423dd7d7408"

      define_method(:install) do
        bin.install "qfex"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/QFEX-org/cli/releases/download/v0.3.0/cli_0.3.0_darwin_arm64.tar.gz"
      sha256 "55196cdf20f9c753ae467bb75d050e396f451f89d6fbcf1d65e12fd9c5a83489"

      define_method(:install) do
        bin.install "qfex"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/QFEX-org/cli/releases/download/v0.3.0/cli_0.3.0_linux_amd64.tar.gz"
      sha256 "db045046c1528d2b3e061c67d31fbb67e270ace259a502f7545c3565a2a1bbbd"
      define_method(:install) do
        bin.install "qfex"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/QFEX-org/cli/releases/download/v0.3.0/cli_0.3.0_linux_arm64.tar.gz"
      sha256 "dcc573b1bd487fbdb58c8c69fbf8a998da70e927a0fc1e8ee63c09ddb67392f9"
      define_method(:install) do
        bin.install "qfex"
      end
    end
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/qfex version")
  end
end
