# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Qfex < Formula
  desc "CLI for the QFEX perpetual futures exchange"
  homepage "https://github.com/QFEX-org/cli"
  version "0.3.13"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/QFEX-org/cli/releases/download/v0.3.13/qfex_0.3.13_darwin_amd64.tar.gz"
      sha256 "b173c9f2410fe9dc8e5e0400446cdd6a91f5e0b4d40c4f16a6f5ca93e33049f3"

      define_method(:install) do
        bin.install "qfex"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/QFEX-org/cli/releases/download/v0.3.13/qfex_0.3.13_darwin_arm64.tar.gz"
      sha256 "05aaf1f7b1e5ff8461a3f82bda275dd237372c372123bc4634ba01d667aba176"

      define_method(:install) do
        bin.install "qfex"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/QFEX-org/cli/releases/download/v0.3.13/qfex_0.3.13_linux_amd64.tar.gz"
      sha256 "5cce394e2d995e67daf5108da9680fa0682e287682fa66d4de1b89682c83354d"
      define_method(:install) do
        bin.install "qfex"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/QFEX-org/cli/releases/download/v0.3.13/qfex_0.3.13_linux_arm64.tar.gz"
      sha256 "559c06acd462ee6e5c32ea4d96df719dfd1df59d015c9a03921d5824fc304d84"
      define_method(:install) do
        bin.install "qfex"
      end
    end
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/qfex version")
  end
end
